apiVersion: v1
kind: Service
metadata:
  name: php-nginx
  namespace: ebuyeralert
spec:
  type: NodePort
  selector:
    app: php-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80